#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --distribution block
#SBATCH --exclude compute102,compute105,compute109,compute111
#SBATCH --time 00:30:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output block1024_3.out
#SBATCH --exclusive

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#export I_MPI_PIN=on
#export I_MPI_DEBUG=4 

#! Run the executable
srun -N 1 -n 1 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 2 -n 2 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 3 -n 3 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 4 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 5 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 6 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 7 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 8 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 9 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 10 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 11 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 12 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 13 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 14 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 15 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 16 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 17 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 18 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 19 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 20 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 21 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 22 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 23 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 24 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 25 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 26 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 27 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 28 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 29 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 30 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 31 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 32 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 33 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 34 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 35 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 36 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 37 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 38 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 39 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 40 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 41 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 42 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 43 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 44 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 45 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 46 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 47 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 48 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 49 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 50 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 51 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 52 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 53 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 54 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 55 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 56 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 57 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 58 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 59 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 60 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 61 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 62 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 63 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 64 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 65 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 66 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 67 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 68 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 69 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 70 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 71 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 72 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 73 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 74 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 75 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 76 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 77 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 78 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 79 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 80 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 81 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 82 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 83 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 84 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 85 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 86 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 87 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 88 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 89 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 90 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 91 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 92 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 93 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 94 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 95 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 96 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 97 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 98 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 99 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 100 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 101 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 102 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 103 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 104 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 105 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 106 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 107 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 108 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 109 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 110 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 111 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -N 4 -n 112 --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat