#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --distribution block
#SBATCH --exclude compute102,compute105,compute109,compute111
#SBATCH --time 00:05:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output d2q9-bgk.out
#SBATCH --exclusive

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#export I_MPI_PIN=on
#export I_MPI_DEBUG=4 

#! Run the executable
srun --ntasks-per-node 28 --mpi=pmi2 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
#srun -n 112 --mpi=pmi2 advixe-cl -collect survey -project-dir ./advisor3 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
#srun -n 112 --mpi=pmi2 advixe-cl -collect tripcounts -flop -stacks -project-dir ./advisor3 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
#srun --mpi=pmi2 advixe-cl -collect=survey ./d2q9-bgk input_256x256.params obstacles_256x256.dat
#srun --mpi=pmi2 advixe-cl -collect=survey ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat